# Generated by Django 4.1 on 2022-08-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='categories',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronicts'), ('Property', 'Property'), ('Toys', 'Toys'), ('Sports and leisure', 'Sports and leisure'), ('Home', 'Home')], max_length=100, null=True),
        ),
    ]
