# Generated by Django 4.1 on 2022-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='image_link',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
