# Generated by Django 4.1 on 2022-08-31 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_created_at_auction_listing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
